### ISSUE TITLE
How to use existing middleware 

### ISSUE THREAD

**Issue by frco9** [blacksmithstudio/blockbase-express#1]
I would like to use the following: https://github.com/expressjs/cors, what is the recommended way to use it ?

Thx

**Comment by frco9** [comment]
The following seems to work : 

```javascript
var cors = require('cors')

module.exports = (app) => {
    return cors();
}
```

**Comment by alxpereira** [comment]
Hey @frco9, 

I confirm, that's the cleanest way 🥇  to implement cors as the `middleware/*.js` files will be automatically wrapped, thanks also to cors itself, already pre-building the callbacks.

Don't hesitate if you need further assistance 👍 
Alex.
