### ISSUE TITLE
Option to avoid returning error details

### ISSUE THREAD

**Issue by Paul-DS** [blacksmithstudio/blockbase-express#2]
Right now the default error middleware looks like that:

```
server.use((err, req, res, next) => {
    if (!config.silent && !errorHandlers.length)
        app.drivers.logger.error('Unhandled server error', err)
    res.status(500).json({message: err.message, stack: err.stack})
})
```

Could you add an option to return a generic error instead of the error details (e.g. for production environment).
The frameworks generally use a `debug` variable in the config file for this purpose, or they choose based on the current environment:
- https://laravel.com/docs/5.5/errors#configuration
- https://sailsjs.com/documentation/reference/configuration/sails-config#?sailsconfigenvironment

Thanks

**Comment by shide1989** [comment]
Hi @Paul-DS, thanks for the feedback
We will publish an update to hide stacktraces when using a production environment in the next release

**Comment by shide1989** [comment]
I added this option in the version 0.2.7. Cheers
